# Generated by Django 5.1.2 on 2024-12-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.class'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.teacher'),
        ),
    ]
