# Generated by Django 5.1.2 on 2024-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_course_class_id_alter_course_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
    ]
