# Generated by Django 5.1.2 on 2024-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teacher_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.ManyToManyField(blank=True, to='myapp.teacher'),
        ),
    ]
