# Generated by Django 5.1.2 on 2024-12-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_chapter_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course_id',
            new_name='course',
        ),
    ]
