# Generated by Django 5.1.2 on 2024-12-11 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_chapter_course_alter_course_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.class'),
        ),
    ]
