# Generated by Django 5.1.2 on 2024-12-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_chapter_course_alter_course_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course',
            new_name='course_id',
        ),
    ]
