# Generated by Django 5.1.2 on 2024-12-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_chapter_course_id_alter_teacher_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='chapter_id',
            field=models.ManyToManyField(blank=True, to='myapp.chapter'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher_id',
            field=models.ManyToManyField(blank=True, to='myapp.teacher'),
        ),
    ]
